global using CustomerFlow.BuildingBlocks.Core.CQRS;
global using CustomerFlow.BuildingBlocks.Core.Exceptions;
global using CustomerFlow.BuildingBlocks.Messaging.IntegrationEvents;
global using CustomerFlow.Core.Domain.AggregatesModel.CustomerAggregate.Abstractions;
global using CustomerFlow.Core.Domain.AggregatesModel.CustomerAggregate.DomainEvents;
global using CustomerFlow.Core.Domain.AggregatesModel.CustomerAggregate.Models;
global using CustomerFlow.Core.Domain.AggregatesModel.CustomerAggregate.ValueObjects;
global using FluentValidation;
global using Microsoft.Extensions.Logging;
