@CustomerFlow= http://localhost:5001

### Get all customers
GET {{CustomerFlow}}/customer
Accept: application/json

### Post a new customer
POST {{CustomerFlow}}/customer
Content-Type: application/json
Accept: application/json

{
    "FirstName": "Keveen",
    "LastName": "Menezes",
    "Email": "joao.silva@email.com",
    "Password": "Senha123",
    "PhoneNumber": "(123)4567890",
    "Address": "Rua Exemplo, 123",
    "City": "São Paulo",
    "State": "SP",
    "ZipCode": "01000-000",
    "Country": "Brasil"
}