// <auto-generated />
using System;
using CustomerFlow.Infra.CommandRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerFlow.Infra.CommandRepository.Migrations
{
    [DbContext(typeof(CustomerFlowDbContext))]
    [Migration("20250625061825_AdicionarTabelaCliente")]
    partial class AdicionarTabelaCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CustomerFlow.Core.Domain.AggregatesModel.CustomerAggregate.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<int?>("PayFrequencyId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phoneNumber");

                    b.Property<Guid?>("PublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("publicId");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("state");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PayFrequencyId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CustomerFlow.Core.Domain.AggregatesModel.CustomerAggregate.Models.PayFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<int>("CountSizeFlux")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("PayrollDiscountsPerYear")
                        .HasColumnType("int");

                    b.Property<int>("PeriodsPerYear")
                        .HasColumnType("int");

                    b.Property<int>("SizeFlux")
                        .HasColumnType("int");

                    b.Property<int>("SumSizeFlux")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PayFrequencies");
                });

            modelBuilder.Entity("CustomerFlow.Core.Domain.AggregatesModel.CustomerAggregate.Models.Customer", b =>
                {
                    b.HasOne("CustomerFlow.Core.Domain.AggregatesModel.CustomerAggregate.Models.PayFrequency", "PayFrequency")
                        .WithMany()
                        .HasForeignKey("PayFrequencyId");

                    b.Navigation("PayFrequency");
                });
#pragma warning restore 612, 618
        }
    }
}
